sortwai/operator/urls.py
from sortwai.operator.views import document, category
from django.urls import path
app_name = 'operator'

urlpatterns = [
    path('document/', document.DocumentCreateView.as_view(), name='document_create'),
    path('documents/', document.DocumentListView.as_view(), name='document_list'),
    path('categories/', category.CategoryListView.as_view(), name='category_list'),
]

sortwai/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from sortwai.waste.views import (
    CategoryListView,
    ChatWidgetView,
    DocumentListView,
    ImageFormView,
    LocationListView,
    ScannerView,
    change_location,
    get_city,
    handle_scan,
    query_request,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", CategoryListView.as_view(), name="category_list"),
    path("docs/", DocumentListView.as_view(), name="document_list"),
    path("locations/", LocationListView.as_view(), name="location_list"),
    path("scanner/", ScannerView.as_view(), name="scanner"),
    path("image/", ImageFormView.as_view(), name="image"),
    path("scanner/<str:code>", handle_scan, name="scanner_product"),
    path("get_location/", get_city, name="get_city"),
    path("change_municipality/", change_location, name="change_municipality"),
    path("query_request/", query_request, name="query_request"),
    path("chat/", ChatWidgetView.as_view(), name="chat_widget"),
    path("operator/", include("sortwai.operator.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sortwai/operator/views/category.py
from django.db.models import QuerySet
from django.views.generic import ListView

from sortwai.waste.models import Category
from sortwai.waste.views import get_active_municipality


class CategoryListView(ListView):
    model = Category
    template_name = 'category_list.html'

    def get_queryset(self) -> QuerySet[Category]:
        municipality = get_active_municipality(self.request)
        objects = Category.objects.filter(municipality=municipality).all()
        return objects

sortwai/operator/views/document.py
from django.db.models import QuerySet
from django.urls import reverse
from django.views.generic import CreateView, ListView

from sortwai.waste.models import Document, Category
from sortwai.waste.views import get_active_municipality
from sortwai.waste.document import import_document, create_objects_from_document


class DocumentCreateView(CreateView):
    model = Document
    fields = ['name', 'text']
    template_name = 'document_form.html'
    success_url = 'operator:document_list'

    def get_success_url(self) -> str:
        return reverse('operator:document_list')

    def form_valid(self, form):
        municipality = get_active_municipality(self.request)
        if not municipality:
            raise ValueError("No active municipality found!")
        form.instance.municipality = municipality
        resp =  super().form_valid(form)
        upload = import_document(form.instance.id)
        create_objects_from_document(form.instance.name, municipality.id)
        return resp
class DocumentListView(ListView):
    model = Document
    template_name = 'document_list.html'

    def get_queryset(self) -> QuerySet[Document]:
        municipality = get_active_municipality(self.request)
        objects = Document.objects.filter(municipality=municipality).all()
        return objects

sortwai/operator/templates/category_list.html
{% extends 'operator_base.html' %}
{% block main %}
{% for object in object_list %}
    <div class="card card--category fade-in">
        <div class="card__content">
            <h2 class="card__title">{{ object.name }}</h2>
            {{ object.description|linebreaks }}

            <div class="waste_detail">
                {% if object.do %}
                    <ul class="waste_detail__item waste_detail__item--do">
                        {% for do in object.do.splitlines %}
                            <li>
                                <iconify-icon icon="mdi:check-circle-outline"></iconify-icon>
                                {{ do }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if object.dont %}
                    <ul class="waste_detail__item waste_detail__item--dont">
                        {% for dont in object.dont.splitlines %}
                            <li>
                                <iconify-icon icon="mdi:close-circle-outline"></iconify-icon>
                                {{ dont }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="waste_destination">
                <iconify-icon class="waste_destination__arrow" icon="mdi:arrow-right"></iconify-icon>
                <div class="waste_destination__name waste_destination__name--{{ object.target.color }}">
                    {{ object.target.name }}
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock main %}

sortwai/operator/templates/document_form.html
{% extends 'operator_base.html' %}
{% block main %}
    <form action="{% url 'operator:document_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock main %}

sortwai/operator/templates/document_list.html
{% extends 'operator_base.html' %}
{% block main %}
    <h2 class="title">Dokumenty odpadového hospodárstva</h2>
    <ul>
        {% for object in object_list %}
            <li>
                <a>{{ object.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock main %}

sortwai/operator/templates/operator_base.html
{% extends 'true_base.html' %}
    {% block content %}
    <div class="container">
    <a href="{% url 'operator:document_create' %}">CREATE DOCUMENT</a>
    <a href="{% url 'operator:document_list' %}">LIST DOCUMENTS</a>
    <a href="{% url 'operator:category_list' %}">LIST CATEGOREIS</a>
    {% block main %}
    {% endblock main %}
    {% endblock content %}
    </div>